#Deb S 
#Date 12 July 2019

import os
import smtplib 
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def emailWith(directory, sender, recipients, file,textToSend):
    #build MIME Multiplart message
    
    msg = MIMEMultipart() 
    msg['From'] = sender 
    msg['To'] = ", ".join(recipients)  
    msg['Subject'] = 'Test Email from '+ sender +' with Python smtplib'
    # make the msg body
    msg.attach(MIMEText(textToSend, 'plain')) 

    with open(directory+'/'+file, "r") as f:
        attachment = MIMEText(f.read())
        attachment.add_header('Content-Disposition', 'attachment', filename='attachment_name') 
        msg.attach(attachment)
    
    smtpserver = smtplib.SMTP('smtp.company.com')
    #my the following line is not needed 
    #smtpserver.starttls()
    # log in is not needed for my case when I am in office network or VNP
    # smtpserver.login('username','password')
    smtpserver.ehlo_or_helo_if_needed()
    #print ('ehlo',server.ehlo_resp)
    try:
        smtpserver.sendmail(sender, recipients, msg.as_string())
    except:
        print ('Could not sent the mail')
    smtpserver.quit() 

dir = r'c:/Documents/mails/attachment'
sender = 'name.surname@company.com'
recipients = ['employee1.surname@company.com', 'employee2.surname@company.com']
file ='attachement.txt'
body = 'This is a autogenerated mail. Please do not reply'

emailWith(directory=dir,sender=sender,recipients=recipients,file=file,textToSend=body)
